-- Wipe the questions, ballots and discussion, seed 250 fresh questions -- ten
-- in each of the 25 country forums -- and create five test agents, one per
-- model, every one small enough for a 12 GB RTX 3060. Pairs with vote_all.py, whose
-- token list matches this one.
--
-- The questions contain non-ASCII text (Türkiye, São Paulo, ...), and
-- Windows PowerShell 5 mangles that when piping into a program. So copy the
-- file into the container and run it there instead:
--
--   docker compose cp reset_and_seed.sql postgres:/tmp/reset_and_seed.sql
--   docker compose exec postgres psql -U vote -d vote -v ON_ERROR_STOP=1 -f /tmp/reset_and_seed.sql
--
-- Run it after the updated app has started once: the app creates the forums
-- table and the 25 country forums at startup, and this file puts questions
-- into them.
--
-- Safe to re-run: it only ever removes the test accounts (@dd.test) and the
-- questions. Real accounts, yours included, are untouched -- the questions are
-- posted as the oldest real account, which is normally you. Forums are kept.
--
-- WARNING: the test accounts have PREDICTABLE tokens (dd-test-01 ... dd-test-05)
-- so the voting script needs no configuration. Fine on localhost, unacceptable
-- on a public instance. Delete them before you publish:
--
--   DELETE FROM users WHERE email LIKE '%@dd.test';

SET client_encoding TO 'UTF8';

BEGIN;

-- The questions are posted by the oldest account that is not a test one. With
-- no such account the insert below would select nothing and quietly create no
-- questions, which looks like success. Fail loudly instead, before anything
-- has been deleted.
DO $guard$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM users WHERE email NOT LIKE '%@dd.test') THEN
        RAISE EXCEPTION 'No real account to author the questions. Register '
                        'yourself on the site first, then run this again.';
    END IF;
END $guard$;

-- The questions go into the country forums, which the app creates when it
-- starts. Without them every question would land in no forum at all.
DO $guard$
BEGIN
    IF to_regclass('forums') IS NULL
       OR (SELECT count(*) FROM forums WHERE kind = 'country') < 25 THEN
        RAISE EXCEPTION 'The country forums are missing. Start the updated app '
                        '(docker compose up -d --build) once, then run this again.';
    END IF;
END $guard$;


-- TRUNCATE rather than DELETE: it does not fire the per-row tally triggers,
-- so this is instant. RESTART IDENTITY puts /i/1 back as the first question.
-- Every table referencing issues is named -- not CASCADE, which would silently
-- empty whatever comes to reference issues next. A new table stops this script
-- with an error instead of being quietly wiped by it.
TRUNCATE notifications, comment_votes, comments, votes, issues RESTART IDENTITY;

-- Old test accounts go, whatever tier created them, so there are never stale
-- agents left voting under a model they no longer run. Their agents cascade.
DELETE FROM users WHERE email LIKE '%@dd.test';

-- --- five test accounts, one model each ---------------------------------------
-- The five strongest general models that fit whole in an RTX 3060's 12 GB,
-- each from a different lab, so a disagreement is between different training
-- rather than between sizes of one family. Every one is under 10 GB at the
-- default 4-bit quantization, leaving room for the context.

CREATE TEMP TABLE test_models (slug text, model text, token text) ON COMMIT DROP;
INSERT INTO test_models VALUES
    ('gemma4-12b',     'gemma4:12b',       'dd-test-01'),   -- Google
    ('qwen35-9b',      'qwen3.5:9b',       'dd-test-02'),   -- Alibaba
    ('ministral3-14b', 'ministral-3:14b',  'dd-test-03'),   -- Mistral
    ('phi4-14b',       'phi4:14b',         'dd-test-04'),   -- Microsoft
    ('granite42-8b',   'granite4.2:8b',    'dd-test-05');   -- IBM

INSERT INTO users (email, email_canonical, display_name, username,
                   password_hash, status, email_verified, note)
SELECT slug || '@dd.test', slug || '@dd.test', slug, slug,
       NULL,                    -- no password: these cannot be logged into
       'approved', true, 'local test agent'
  FROM test_models;

INSERT INTO agents (user_id, name, model_name, token_hash)
SELECT u.id, u.username || '-agent', m.model,
       encode(sha256(m.token::bytea), 'hex')
  FROM test_models m JOIN users u ON u.username = m.slug;

-- --- 250 questions, ten per country forum -------------------------------------
-- Written to spread across all four outcomes: some clearly worth doing and
-- harmless, some worth doing with a real cost, some mostly harmful, and some
-- that simply do not matter much either way. The posting times interleave the
-- countries, so the All page shows a mix rather than 10 of one country.

INSERT INTO issues (author_id, forum_id, title, body, closes_at, created_at)
SELECT (SELECT id FROM users WHERE email NOT LIKE '%@dd.test'
         ORDER BY id LIMIT 1),
       f.id, t.title, t.body,
       now() + interval '14 days',
       now() - (t.ord * interval '7 minutes')
  FROM (VALUES
 (1,'china',$t$Should every metro station in Chinese cities have a publicly accessible defibrillator (AED)?$t$,$b$Cardiac arrests in busy stations are survivable if an AED is used within minutes. Placing devices and training staff in stations across cities from Shenzhen to Xi'an costs relatively little per station and could save many lives.$b$),
 (2,'india',$t$Should Indian cities set up shaded bus shelters with free drinking water during summer heatwaves?$t$,$b$Outdoor workers, commuters and elderly people waiting for buses face serious heat stress in cities like Delhi, Ahmedabad and Nagpur. Municipal corporations would pay for shade structures and water dispensers, a modest cost compared with heat-related illness.$b$),
 (3,'united-states',$t$Should the federal government fully fund replacing lead water service lines in older US cities?$t$,$b$Many older cities in the Midwest and Northeast still have lead pipes that can contaminate drinking water, harming children's development. Full federal funding would speed replacement, at a cost of many billions of dollars spread over years.$b$),
 (4,'indonesia',$t$Should Indonesia regularly test and maintain tsunami warning sirens in all coastal villages of Sulawesi?$t$,$b$Coastal communities in Sulawesi face earthquake and tsunami risk, and warning systems only help if they work when needed. Regular testing and repairs cost modest amounts of rupiah and can save lives in minutes-long warning windows.$b$),
 (5,'brazil',$t$Should Brazil fund more rainwater cisterns for rural households in the semi-arid Sertão?$t$,$b$Families in the dry northeastern interior often depend on water trucks during long droughts. Household cisterns that store rainy-season water are simple and durable, though the programme needs federal money and local builders.$b$),
 (6,'russia',$t$Should Russian cities install heated, enclosed shelters at their busiest winter bus stops?$t$,$b$Long waits at bus stops in deep frost are hard on older people and children. Enclosed, heated shelters would make public transport more usable in winter, though cities would pay for electricity and maintenance.$b$),
 (7,'pakistan',$t$Should Pakistan install rooftop solar panels at all rural Basic Health Units?$t$,$b$Power cuts disrupt vaccine refrigeration, lighting and equipment in village clinics. Solar panels with batteries would keep services running and cut fuel costs, though they need upfront investment and occasional maintenance.$b$),
 (8,'mexico',$t$Should Mexico fund rainwater-harvesting systems for public schools in the Valle de México?$t$,$b$Many schools in Mexico City and the State of Mexico face irregular water supply and rely on water trucks. Rooftop catchment tanks and filters would keep toilets and handwashing running; the cost is installation plus yearly maintenance from education budgets.$b$),
 (9,'japan',$t$Should Japan require rural bus operators to publish their timetables as open data for map apps?$t$,$b$In many rural areas, bus times are only on paper or PDF, so residents and visitors cannot plan trips in map apps. Open data would help older residents and tourists; small operators would need modest help converting their schedules.$b$),
 (10,'nigeria',$t$Should rural primary health centres in Nigeria get solar power to keep vaccines cold?$t$,$b$Many rural clinics rely on unreliable grid power or costly diesel generators, so vaccines can spoil. Solar systems with batteries would cost states money upfront and need trained technicians for upkeep, but would cut fuel bills over time.$b$),
 (11,'philippines',$t$Should new schools in typhoon-prone Philippine provinces be built to double as evacuation centres?$t$,$b$Schools often shelter families during typhoons but are not designed for it. Stronger roofs, raised floors, toilets and water tanks would make them safer; the cost is higher construction budgets in pesos per classroom.$b$),
 (12,'egypt',$t$Should Egypt expand drip-irrigation subsidies for smallholder farmers in the Nile Delta?$t$,$b$Flood irrigation loses much of the Nile water Egypt depends on. Helping small farmers switch to drip lines would save water and can raise yields; the cost is public funding and training through agricultural extension offices.$b$),
 (13,'vietnam',$t$Should Hà Nội add shaded, covered waiting areas at its busiest city bus stops?$t$,$b$Many bus stops offer little cover from summer heat and monsoon downpours, which discourages riders. Adding roofs and seating at the most-used stops would cost a modest sum in dong and mainly benefit commuters, students and older passengers.$b$),
 (14,'germany',$t$Should every German district let residents register a car fully online?$t$,$b$Registering a vehicle often still means visiting an office and waiting for an appointment. A complete online process in every district would save residents time, though local authorities would need to update their IT systems.$b$),
 (15,'bangladesh',$t$Should Bangladesh build more cyclone shelters in coastal Khulna and Barisal with room for livestock?$t$,$b$Coastal families sometimes refuse to evacuate because they cannot leave cattle and goats behind. Shelters with animal space would save more lives and livelihoods, though they cost more to build and maintain.$b$),
 (16,'turkey',$t$Should İstanbul mark every emergency assembly area with lit signs and QR-code maps?$t$,$b$After an earthquake, people need to find safe gathering points quickly. Clear, lit signs with scannable maps in each neighbourhood would help residents and visitors, at a modest cost to district municipalities.$b$),
 (17,'iran',$t$Should Iranian cities fit apartment buildings with smart water meters that flag leaks?$t$,$b$Many cities face water stress, and hidden leaks waste a lot of supply. Smart meters would alert residents and utilities to unusual use; the cost in rials is moderate and would mostly be recovered from saved water.$b$),
 (18,'united-kingdom',$t$Should every public defibrillator in the UK be registered on a single national map for 999 callers?$t$,$b$When someone has a cardiac arrest, call handlers can direct bystanders to the nearest defibrillator only if they know where it is. Registration costs owners a few minutes of form-filling and could save lives in towns and villages.$b$),
 (19,'thailand',$t$Should Bangkok build covered, shaded walkways linking BTS and MRT stations to nearby bus stops?$t$,$b$Many commuters walk the last few hundred metres in heavy heat or monsoon rain. Covered walkways would make public transport more usable for older people and parents with children, at a moderate construction cost to the city.$b$),
 (20,'france',$t$Should France fund secure, covered bike parking at every regional TER railway station?$t$,$b$Many people living in villages could cycle to their nearest station if they knew their bike would be safe. Secure shelters cost relatively little in euros and would help rural commuters leave the car at home.$b$),
 (21,'italy',$t$Should Italy fund earthquake-proofing of school buildings in seismic areas of the Apennines?$t$,$b$Many schools in central and southern Italy are old and were not built to modern seismic standards. Retrofitting them protects pupils and teachers, costing public funds and temporary disruption during works.$b$),
 (22,'south-africa',$t$Should South African municipalities fund a large programme to repair leaking water pipes?$t$,$b$A large share of treated water in many towns is lost through leaks before it reaches taps. Fixing pipes and meters would stretch existing supply further, though it needs skilled crews and steady funding in rand.$b$),
 (23,'south-korea',$t$Should Seoul show live lift and escalator status for every subway station in its transit apps?$t$,$b$Wheelchair users, parents with prams and older riders often find a station lift out of service only after arriving. Publishing live status would let them plan routes in advance, at a modest cost for sensors and data feeds.$b$),
 (24,'spain',$t$Should Spain fund shade canopies and trees in every public schoolyard in its hottest regions?$t$,$b$In parts of Andalucía, Murcia and Extremadura, bare concrete playgrounds become dangerously hot in June and September. Planting trees and adding shade would protect children, at a manageable cost to education budgets.$b$),
 (25,'colombia',$t$Should Bogotá add secure, covered bicycle parking at every major TransMilenio station?$t$,$b$Many people would cycle to the bus network if they had somewhere safe to leave their bike. Guarded, covered racks would make bike-and-bus trips easier and cut car use, at a modest cost for space and staff.$b$),
 (26,'china',$t$Should China offer free HPV vaccination to all girls aged around 13 nationwide?$t$,$b$Vaccination sharply reduces the risk of cervical cancer later in life. Some provinces already fund it; a national programme would remove regional gaps, at a cost to health budgets that is small relative to later treatment costs.$b$),
 (27,'india',$t$Should Indian Railways provide step-free access, ramps and lifts at every major junction station?$t$,$b$Many passengers with disabilities, older travellers and families with heavy luggage struggle with stairs and footbridges. The upgrades would take years and several thousand crore rupees, spread across the railway budget.$b$),
 (28,'united-states',$t$Should every US public middle and high school keep naloxone on hand to reverse opioid overdoses?$t$,$b$Opioid overdoses sometimes happen on school grounds, and naloxone is safe and easy to use. Stocking it and training staff costs districts little, while giving a real chance of saving a student's or visitor's life.$b$),
 (29,'indonesia',$t$Should more Indonesian cities release Wolbachia mosquitoes to reduce dengue fever cases?$t$,$b$Mosquitoes carrying Wolbachia bacteria are less able to spread dengue, and trials such as the one in Yogyakarta showed strong results. Scaling up needs community engagement and funding but poses little risk to people.$b$),
 (30,'brazil',$t$Should São Paulo build protected bike lanes linking outer neighbourhoods to metro stations?$t$,$b$Many residents on the city's edges face long bus rides just to reach the metro. Safe cycle lanes would offer a cheap, faster option, though some street parking and road space for cars would be lost.$b$),
 (31,'russia',$t$Should Russia fund telemedicine links for village clinics in remote northern and Siberian regions?$t$,$b$Patients in remote settlements may travel hundreds of kilometres to see a specialist. Video consultations with regional hospitals would save trips, though they need reliable internet and trained local staff.$b$),
 (32,'pakistan',$t$Should districts along the Indus send free SMS flood warnings to every mobile phone in threatened areas?$t$,$b$Early warnings give families in Sindh and southern Punjab time to move people and livestock to safety before floods. The system would use existing mobile networks, making it a low-cost way to reduce loss of life.$b$),
 (33,'mexico',$t$Should rural clinics in Oaxaca and Chiapas get solar backup power for their vaccine refrigerators?$t$,$b$Power cuts in remote clinics can spoil vaccines and insulin. Solar panels with batteries would keep cold storage running through outages; the cost is purchase and training local staff to maintain the equipment.$b$),
 (34,'japan',$t$Should Japanese municipalities open air-conditioned public buildings as free cooling shelters in heatwaves?$t$,$b$Summer heat sends many older people to hospital each year. Opening libraries, community centres and town halls as cooling spots would give free relief; the cost is longer opening hours, staff time and electricity.$b$),
 (35,'nigeria',$t$Should Nigerian states publish flood-risk maps for towns along the Niger and Benue rivers?$t$,$b$Seasonal floods along the two rivers regularly damage homes and farms. Public maps would help families, builders and local governments plan where to live and plant, at the cost of surveying work and keeping the maps up to date.$b$),
 (36,'philippines',$t$Should Philippine barangays get river-level sensors linked to automatic flood sirens?$t$,$b$Flash floods can rise faster than residents hear warnings. Low-cost sensors on rivers feeding sirens in barangays would give families time to move; the cost is equipment, power backup and local upkeep.$b$),
 (37,'egypt',$t$Should Cairo add signalised pedestrian crossings on major roads near schools?$t$,$b$Children in Cairo often cross wide, fast roads with no safe crossing. Signals, marked crossings and speed bumps near schools would reduce injuries; drivers would face slightly slower journeys at those points.$b$),
 (38,'vietnam',$t$Should Vietnam fund saltwater-intrusion monitoring stations across Mekong Delta rice districts?$t$,$b$Seawater pushing inland during dry seasons can ruin rice and fruit harvests. A network of sensors with SMS alerts would tell farmers when to close sluice gates or delay pumping, at a fairly small cost to provincial budgets.$b$),
 (39,'germany',$t$Should German cities plant more shade trees in schoolyards to cool them during heatwaves?$t$,$b$Asphalt schoolyards can get very hot in summer, which is hard on children. Planting trees and removing some paving would cost cities a modest amount in euros and bring cooler, greener spaces for decades.$b$),
 (40,'bangladesh',$t$Should Bangladesh test every rural tube well for arsenic and paint the spouts of safe ones?$t$,$b$Arsenic in groundwater remains a hidden health risk in many villages. Regular testing with clear red or green markings lets families choose safe wells, at the cost of field staff, test kits and repeat visits.$b$),
 (41,'turkey',$t$Should Türkiye require independent seismic checks of all older public school buildings?$t$,$b$Schools built before stricter building codes may be at risk in an earthquake. Independent engineering checks would show which buildings need strengthening first; the cost is inspectors’ fees and some disruption during surveys.$b$),
 (42,'iran',$t$Should Iran offer free hearing and vision checks to every first-grade pupil?$t$,$b$Undetected sight or hearing problems can hold children back for years. Screening in schools by trained nurses would catch issues early, at a modest cost to the health budget, and help families who can’t easily reach a clinic.$b$),
 (43,'united-kingdom',$t$Should councils offer free loft and cavity wall insulation to low-income households in older homes?$t$,$b$Much of the UK's housing is old, draughty and costly to heat in winter. Free insulation would cut energy bills and cold-related illness, paid for from public funds at a few thousand pounds per home.$b$),
 (44,'thailand',$t$Should Thailand fund village flood sirens and SMS alerts for flash floods in its northern provinces?$t$,$b$Flash floods in hilly areas such as Chiang Rai and Nan can arrive with little warning. Simple sirens linked to river gauges, plus phone alerts, would give residents time to move, for a modest cost in equipment and upkeep.$b$),
 (45,'france',$t$Should French towns replace tarmac school playgrounds with trees and shaded green space?$t$,$b$Paved school yards can become very hot during summer heatwaves. Greener playgrounds, like the 'cours oasis' tried in Paris, keep children cooler and absorb rainwater, at an upfront cost to municipalities.$b$),
 (46,'italy',$t$Should Italy invest in repairing leaks in the ageing water networks of southern regions?$t$,$b$Old pipes in many towns lose a large share of water before it reaches homes, and summers are getting drier. Repairs would improve supply for households and farms, paid for over years in euros.$b$),
 (47,'south-africa',$t$Should South Africa install rooftop solar and batteries on public health clinics?$t$,$b$Power cuts can disrupt vaccine fridges, lights and equipment at clinics. Solar with battery backup would keep essential care running, at an upfront cost that is partly repaid through lower electricity bills.$b$),
 (48,'south-korea',$t$Should schools be sent automatic alerts on high fine-dust days so outdoor PE can be moved indoors?$t$,$b$On spring days with heavy fine dust, some schools still run outdoor lessons because warnings reach teachers late. Linking air-quality forecasts directly to school systems would protect pupils' lungs, with minor setup costs for education offices.$b$),
 (49,'spain',$t$Should Spain prioritise fixing leaking municipal water pipes before building new reservoirs?$t$,$b$Many towns lose a large share of treated water through old, leaky networks, while droughts are growing more frequent. Repairing pipes first would save water cheaply, though it means disruptive street works in affected towns.$b$),
 (50,'colombia',$t$Should Colombia install landslide sensors and warning sirens in hillside neighbourhoods at risk?$t$,$b$Heavy rains regularly trigger landslides on the steep slopes around cities like Medellín and Manizales. Early-warning sensors and sirens would give residents time to evacuate, for a relatively small public investment.$b$),
 (51,'china',$t$Should flood-prone cities along the Yangtze expand 'sponge city' features such as permeable paving and wetland parks?$t$,$b$Heavy summer rains regularly overwhelm drains in cities like Wuhan. Green spaces and paving that soak up water reduce flooding and recharge groundwater, though the retrofits take time and local government funding.$b$),
 (52,'india',$t$Should new government buildings in India be required to include rooftop rainwater harvesting?$t$,$b$Groundwater is falling in many Indian cities, and government offices, schools and hospitals have large roofs that could recharge aquifers during the monsoon. It adds a small construction cost and needs basic upkeep each year.$b$),
 (53,'united-states',$t$Should schools in wildfire-prone Western states install air purifiers in every classroom?$t$,$b$Wildfire smoke from California to Washington increasingly affects air quality during the school year. Portable HEPA purifiers are fairly cheap and protect children's lungs, though districts must pay for filters and replacements.$b$),
 (54,'indonesia',$t$Should every public primary school in Indonesia have working handwashing stations with soap and clean water?$t$,$b$Handwashing reduces diarrhoea and respiratory infections that keep children out of school. Many schools in rural areas lack reliable water; building and maintaining stations is a small cost for local education budgets.$b$),
 (55,'brazil',$t$Should the SUS give free eyeglasses to public-school children who fail a vision test?$t$,$b$Children who cannot see the board well often fall behind in class without anyone noticing. Screening in schools and free glasses through the public health system would cost money but is relatively cheap per child helped.$b$),
 (56,'russia',$t$Should Moscow and Saint Petersburg add lifts to older metro stations that lack step-free access?$t$,$b$Many older stations have only long escalators or stairs, which shut out wheelchair users and parents with prams. Adding lifts is expensive and disruptive to build, but opens the network to more riders.$b$),
 (57,'pakistan',$t$Should every government girls' school in Pakistan have clean, private, working toilets?$t$,$b$A lack of safe toilets is a common reason older girls miss school or drop out. Building and maintaining facilities costs provincial education departments money, but it directly supports attendance and health.$b$),
 (58,'mexico',$t$Should Mexican public universities publish free open-licence versions of their first-year textbooks?$t$,$b$Students often spend hundreds of pesos per course on books. Open online editions written by university faculty would lower costs for students nationwide; universities would need to pay authors and editors for the extra work.$b$),
 (59,'japan',$t$Should Japan make earthquake-resistance checks free for wooden houses built before 1981?$t$,$b$Homes built before Japan's stricter 1981 building standard are more likely to collapse in strong quakes. Free inspections would help owners, many of them elderly, decide on retrofits; the cost is paid by national and local budgets.$b$),
 (60,'nigeria',$t$Should Lagos State add more scheduled water ferry routes linking Ikorodu, Badagry and Lagos Island?$t$,$b$Road traffic into Lagos Island can take hours, while the lagoon is underused. More regular ferries would need new jetties, safety inspections and life-jacket enforcement, paid for by the state and partly by fares.$b$),
 (61,'philippines',$t$Should overseas Filipino workers be able to renew key government documents fully online?$t$,$b$Workers abroad often travel far to embassies or wait until home visits to renew records. Secure online renewal would save time and money; agencies would need to invest in systems and identity checks.$b$),
 (62,'egypt',$t$Should Egypt digitise land title records so rural families can check ownership online?$t$,$b$Paper land records in many governorates are hard to access and easy to dispute. Online records would reduce conflicts and help families use land as loan collateral; the cost is scanning, verification and staff training.$b$),
 (63,'vietnam',$t$Should Vietnamese public primary schools offer free swimming lessons to every child?$t$,$b$With long coastlines, rivers and seasonal floods, knowing how to swim can save lives. Schools would partner with local pools or safe river sites; the main costs are instructors, lifeguards and some lesson time.$b$),
 (64,'germany',$t$Should Germany make every regional railway station step-free by 2035?$t$,$b$Stairs-only platforms shut out wheelchair users, parents with prams and older travellers. A funded programme of ramps and lifts would improve access nationwide, at a significant but spread-out cost to federal and state budgets.$b$),
 (65,'bangladesh',$t$Should Dhaka build raised, shaded footpaths along main roads so walkers can avoid monsoon flooding?$t$,$b$Many people in Dhaka walk to work, and waterlogged roads in the monsoon make that dangerous. Raised, covered footpaths would need city funds and could narrow some roadside space used by vendors.$b$),
 (66,'turkey',$t$Should Türkiye let pharmacists renew routine chronic-illness prescriptions without a new doctor visit?$t$,$b$Patients with stable conditions such as high blood pressure often queue just to renew the same medicine. Letting pharmacists renew them for a limited period would free up doctors, with safeguards and referral rules.$b$),
 (67,'iran',$t$Should the Tehran Metro run later into the night on Thursdays and Fridays?$t$,$b$Longer service at the weekend would give people a safe, cheap way home from visits, events and late shifts. The costs are extra staff hours and electricity, and less overnight time for maintenance.$b$),
 (68,'united-kingdom',$t$Should NHS GP surgeries be required to offer online appointment booking alongside phone lines?$t$,$b$Long queues on the phone at 8am frustrate patients. Online booking would give another route in, while keeping phone and in-person options for people who are not online. Some smaller practices would need help with the software.$b$),
 (69,'thailand',$t$Should Thai public primary schools offer free swimming lessons to every pupil?$t$,$b$Drowning is a serious risk for children in a country of rivers, canals and coastline. Schools would partner with local pools or safe open water sites, costing some baht per pupil and requiring trained instructors.$b$),
 (70,'france',$t$Should France fund mobile medical vans to visit rural villages that have no resident doctor?$t$,$b$Some rural areas struggle to attract GPs, leaving older residents to travel far for basic care. Regular visits by vans with a nurse or doctor would fill the gap, paid for by regional health agencies.$b$),
 (71,'italy',$t$Should Italy offer a low-cost monthly regional rail pass for students and commuters?$t$,$b$A cheaper pass would make daily trains more attractive than driving on busy roads around cities such as Milano and Napoli. The state and regions would need to cover some lost ticket revenue.$b$),
 (72,'south-africa',$t$Should South Africa build more lit pedestrian bridges over busy highways near residential areas?$t$,$b$Many people walk across fast roads to reach work, schools and taxi ranks, and pedestrian deaths are a serious problem. Safe, well-lit footbridges would cost money to build and maintain but could prevent many injuries.$b$),
 (73,'south-korea',$t$Should public health centres offer a free yearly hearing check to everyone over 65?$t$,$b$Untreated hearing loss is linked to isolation and faster cognitive decline in older people. Free annual checks at local public health centres would catch it earlier, costing the health budget a modest amount for staff and equipment.$b$),
 (74,'spain',$t$Should patients be able to see their health records from any region in one national app?$t$,$b$People who move or fall ill while travelling between regions often find doctors cannot see their history. A shared, secure app would improve care and cut repeated tests, with costs for linking regional health systems.$b$),
 (75,'colombia',$t$Should Colombia fund monthly mobile health clinics for remote villages on the Pacific coast?$t$,$b$Communities along rivers in Chocó and Nariño can be days from a hospital. Regular visits by boat-based clinics would bring vaccinations, prenatal care and check-ups, at a real but manageable cost to the health system.$b$),
 (76,'china',$t$Should China require owners of older e-bikes to replace their batteries with certified safer models?$t$,$b$Battery fires in apartment corridors have caused deaths. Mandatory replacement would cut that risk, but the cost of several hundred yuan falls heavily on delivery riders and lower-income commuters who rely on their e-bikes.$b$),
 (77,'india',$t$Should Bengaluru introduce a congestion charge for private cars entering the central business district at peak hours?$t$,$b$The charge aims to cut traffic jams and fund buses and the Namma Metro. The cost falls on drivers and small businesses in the centre, and it may push traffic onto surrounding neighbourhoods unless public transport improves fast.$b$),
 (78,'united-states',$t$Should Congress raise the federal gas tax by 10 cents a gallon and index it to inflation for road repairs?$t$,$b$The gas tax has not risen in decades and the Highway Trust Fund regularly runs short. A rise would fund bridges and roads, but costs fall on drivers, especially rural and lower-income households who drive long distances.$b$),
 (79,'indonesia',$t$Should Indonesia introduce an excise tax on sugary drinks to reduce diabetes and obesity?$t$,$b$A tax could lower sugar consumption and raise rupiah for health programmes. But it raises prices for consumers, may hurt small warung shops that sell drinks, and the burden falls proportionally more on lower-income households.$b$),
 (80,'brazil',$t$Should Brazil require soy traders to prove shipments did not come from newly cleared Cerrado land?$t$,$b$The Cerrado savanna is losing native vegetation to farming, affecting water supplies and wildlife. Tracing rules would protect it, but they add paperwork and costs for farmers and could reduce income in farming regions.$b$),
 (81,'russia',$t$Should Siberian cities such as Krasnoyarsk phase out coal-fired district heating?$t$,$b$Coal heating contributes to heavy winter smog in some Siberian cities. Switching to gas or cleaner sources would improve air quality, but heating bills could rise and coal-dependent jobs would be lost.$b$),
 (82,'pakistan',$t$Should Punjab close brick kilns near Lahore during the winter smog season?$t$,$b$Kilns are a major source of smoke that worsens winter air quality in Lahore. Seasonal closures would help public health, but kiln workers, many paid daily, would lose income for weeks and construction costs could rise.$b$),
 (83,'mexico',$t$Should Mexico City charge private cars a daily fee to enter the Centro Histórico?$t$,$b$A congestion charge could cut traffic and air pollution in the historic centre and fund better buses. The cost falls on drivers and on shop owners who fear fewer customers, and it may push traffic into surrounding colonias.$b$),
 (84,'japan',$t$Should Japan add a nationwide overnight tourist tax of roughly 1,000 yen per night?$t$,$b$Busy spots such as Kyoto and Mount Fuji face crowding and wear. A tax could fund cleaning, transport and heritage upkeep, but it raises trip costs, may deter budget travellers, and adds paperwork for small inns.$b$),
 (85,'nigeria',$t$Should Nigeria ban imports of used cars older than ten years to reduce air pollution?$t$,$b$Older imported vehicles tend to burn more fuel and emit more fumes in cities like Lagos and Kano. But many families and taxi drivers can only afford older cars, so a ban would raise the price of getting around and hurt used-car dealers.$b$),
 (86,'philippines',$t$Should Metro Manila phase out old diesel jeepneys in favour of cleaner modern vehicles?$t$,$b$Newer units would cut air pollution and improve safety. The cost falls on small operators and drivers who struggle to afford new vehicles, and the classic jeepney is a cherished part of street life.$b$),
 (87,'egypt',$t$Should Egypt raise water tariffs for the heaviest household users in Cairo and Alexandria?$t$,$b$Higher prices for top usage tiers would encourage saving scarce water and fund pipe repairs. The cost falls on large households and those with leaky old plumbing, who may struggle to pay more in Egyptian pounds.$b$),
 (88,'vietnam',$t$Should Hồ Chí Minh City charge cars a congestion fee to enter District 1 at peak hours?$t$,$b$A fee could ease gridlock and air pollution in the city centre and fund buses and the metro. The cost falls on car owners, delivery firms and some shops, which may lose customers who choose to go elsewhere.$b$),
 (89,'germany',$t$Should Germany introduce a general 130 km/h speed limit on the Autobahn?$t$,$b$A limit would likely reduce serious crashes, fuel use and emissions. But many drivers value unrestricted sections, journeys on some routes would take longer, and some see it as an unnecessary restriction.$b$),
 (90,'bangladesh',$t$Should Bangladesh require large garment factories to install rooftop solar panels?$t$,$b$Factories use large amounts of grid and diesel power, and rooftops are often unused. Solar would cut emissions and outages, but the upfront cost falls on manufacturers already under pressure from buyers on price.$b$),
 (91,'turkey',$t$Should İstanbul restrict private cars in the historic peninsula around Sultanahmet?$t$,$b$Fewer cars would mean cleaner air, safer streets and better protection for historic sites. But residents, hotels and shopkeepers would face harder deliveries and access, and some trade could move elsewhere.$b$),
 (92,'iran',$t$Should Iran gradually raise subsidised petrol prices and return the savings as cash transfers?$t$,$b$Low fuel prices encourage heavy use, smuggling and air pollution, and cost the state a great deal. Raising them step by step with cash payments to households could help, but prices of transport and goods would rise too.$b$),
 (93,'united-kingdom',$t$Should water companies in England be required to end routine sewage spills into rivers within ten years?$t$,$b$Storm overflows discharge untreated sewage into rivers and coastal waters. Ending them would clean up swimming spots and wildlife habitats, but upgrading pipes and treatment works would cost billions of pounds, likely paid through higher bills.$b$),
 (94,'thailand',$t$Should Thailand ban open burning of sugarcane and maize fields during the dry season?$t$,$b$Crop burning contributes to the haze that affects Chiang Mai and other northern cities each year. A ban would improve air quality, but many smallholder farmers would face higher costs for harvesting machines or residue removal.$b$),
 (95,'france',$t$Should France strictly cap summer irrigation from rivers in the south-west during droughts?$t$,$b$Low summer flows harm fish and drinking water supply in rivers such as the Garonne. Firm caps would protect them, but maize and fruit farmers could lose crops and income in dry years.$b$),
 (96,'italy',$t$Should Venice require day visitors to book in advance with a daily limit on numbers?$t$,$b$A cap could ease crowding in the historic centre and make life better for residents. But it would restrict access to a world heritage city and reduce income for shops, restaurants and guides that depend on visitors.$b$),
 (97,'south-africa',$t$Should South Africa raise its levy on sugary drinks to reduce diabetes and obesity?$t$,$b$A higher levy could cut sugar consumption and raise revenue for health care. But it would raise prices for consumers and could hurt sugar cane farmers and jobs in KwaZulu-Natal and Mpumalanga.$b$),
 (98,'south-korea',$t$Should Seoul charge a weekday congestion fee for private cars entering the city centre?$t$,$b$A fee of a few thousand won for cars entering central districts like Jongno and Jung-gu could cut traffic and air pollution and fund buses. The cost falls on drivers, delivery firms and small shop owners who depend on car access.$b$),
 (99,'spain',$t$Should Spain freeze new tourist-flat licences in central Barcelona, Madrid and Palma?$t$,$b$Short-term holiday lets are blamed for pushing up rents and emptying historic centres of residents. A freeze could free homes for locals, but owners would lose income and some tourism businesses would see fewer visitors.$b$),
 (100,'colombia',$t$Should Cartagena charge visitors a daily fee to enter its historic walled city?$t$,$b$A small fee in Colombian pesos could pay for restoring colonial buildings and managing crowds. The cost falls on visitors and on local vendors and guides, who may see fewer customers if tourists stay away.$b$),
 (101,'china',$t$Should Chinese cities raise summer electricity prices for the heaviest household users to cut peak demand?$t$,$b$Steeper tiers for top consumers would ease strain on the grid during heatwaves and encourage efficiency. But large or multigenerational households and older people who need air conditioning could face noticeably higher bills.$b$),
 (102,'india',$t$Should Delhi require all diesel autorickshaws and delivery vans to switch to electric within five years?$t$,$b$Cleaner vehicles would cut winter smog and roadside pollution. Drivers, many of whom own a single vehicle, would face large upfront costs even with subsidies, and charging infrastructure is still patchy in many areas.$b$),
 (103,'united-states',$t$Should California let apartment buildings be built on all residential lots near major transit stops?$t$,$b$Allowing more homes near rail and bus lines could ease the housing shortage and cut commutes. Current residents may face more traffic, strained parking and changes to neighbourhood character they value.$b$),
 (104,'indonesia',$t$Should Indonesia ban all new oil palm plantations on peatland in Sumatra and Kalimantan?$t$,$b$Draining peat for palm oil releases huge amounts of carbon and fuels haze-causing fires. A ban would protect the climate and public health, but smallholder farmers and plantation workers would lose a path to income.$b$),
 (105,'brazil',$t$Should Rio de Janeiro charge cruise passengers a visitor fee of 20 reais per day ashore?$t$,$b$The money could fund beach cleaning, tourist policing and upkeep of sites like the Centro waterfront. The cost is that some cruise lines may skip Rio, reducing sales for local guides, vendors and restaurants.$b$),
 (106,'russia',$t$Should Russia ban new hotel construction along the shores of Lake Baikal?$t$,$b$Baikal's clear water and unique wildlife are sensitive to sewage and crowding. A ban would protect the lake, but it would limit jobs and income for local communities that rely on growing tourism.$b$),
 (107,'pakistan',$t$Should Karachi reassess property taxes at current market values to fund water and sanitation?$t$,$b$Outdated valuations mean property tax brings in little revenue while the city's water and sewage systems struggle. Revaluation would raise funds, but homeowners and small landlords would face sharply higher bills.$b$),
 (108,'mexico',$t$Should Mexico cap the number of new hotel rooms allowed along the Riviera Maya coast?$t$,$b$Rapid hotel building near Cancún and Tulum strains water, mangroves and the reef. A cap would protect the coast that draws visitors, but it would limit new construction jobs and investment in Quintana Roo.$b$),
 (109,'japan',$t$Should Japan restart more of its idled nuclear reactors to cut imported fuel costs?$t$,$b$Restarts could lower electricity bills and emissions and reduce reliance on imported gas and coal. The cost is safety risk in an earthquake-prone country, unresolved waste storage, and concern among nearby residents.$b$),
 (110,'nigeria',$t$Should Lagos remove street traders from road shoulders on major highways to ease traffic?$t$,$b$Traders and buyers on road edges slow traffic and create safety risks. Yet street trading is the main income for many households, and clearing them without affordable market space elsewhere would cost livelihoods.$b$),
 (111,'philippines',$t$Should the Philippines ban single-use plastic sachets for products like shampoo and sauces?$t$,$b$Sachets clog drains and worsen floods and marine litter. But many low-income families buy in sachets because they cannot afford larger packs, so a ban would raise their daily costs unless refill options spread.$b$),
 (112,'egypt',$t$Should Egypt limit daily visitor numbers inside the tombs of the Valley of the Kings?$t$,$b$Breath, humidity and crowds slowly damage the painted walls near Luxor. Timed-entry caps would protect them, but some tourists would be turned away, and guides and local businesses could lose income.$b$),
 (113,'vietnam',$t$Should Vietnam stop approving new coal power plants and build offshore wind off the south-central coast?$t$,$b$Offshore wind would cut air pollution and emissions and use strong coastal winds. But it needs large upfront investment and new grid lines, and electricity bills in dong could rise for households and factories in the short term.$b$),
 (114,'germany',$t$Should Germany keep the Deutschlandticket at a low flat monthly price with federal subsidy?$t$,$b$A cheap nationwide ticket makes buses and trains simple and affordable for millions. But it costs billions of euros a year in subsidies, and transport operators say it strains their budgets for upgrades.$b$),
 (115,'bangladesh',$t$Should Dhaka ban cycle rickshaws from its main arterial roads to speed up traffic?$t$,$b$Slow rickshaws mixed with buses and cars add to congestion and accidents. But rickshaw pulling is the main income for many workers, and passengers would lose a cheap, flexible way to make short trips.$b$),
 (116,'turkey',$t$Should Türkiye require new Aegean and Mediterranean hotels to be built well back from the shore?$t$,$b$Larger setbacks would protect beaches, dunes and turtle nesting sites and keep the coast open to the public. But they reduce buildable land, raise costs for investors and could slow tourism jobs in coastal towns.$b$),
 (117,'iran',$t$Should Iran limit water-hungry crops like rice in dry provinces such as Isfahan and Yazd?$t$,$b$Irrigating thirsty crops in arid areas drains rivers and aquifers. Limiting them would protect water supplies for cities and wetlands, but farmers would lose income and need support to switch crops or livelihoods.$b$),
 (118,'united-kingdom',$t$Should the UK build several new reservoirs in south-east England to prepare for drier summers?$t$,$b$The south-east faces growing water shortages as the climate warms and population grows. New reservoirs would secure supply, but they would flood farmland and countryside and take many years and large sums to build.$b$),
 (119,'thailand',$t$Should Bangkok charge private cars a daily fee to enter its central business district?$t$,$b$A congestion charge could cut traffic and fund better buses, but it would add a cost of perhaps tens of baht per day for drivers, including people who live far from rail lines and have few alternatives.$b$),
 (120,'france',$t$Should Marseille limit the number of large cruise ships that can dock in the city each day?$t$,$b$Cruise ships bring visitors and spending, but also air pollution near homes in the port districts. A daily cap would improve air quality while costing local shops, guides and the port some revenue.$b$),
 (121,'italy',$t$Should Rome build a modern waste-to-energy plant to reduce its reliance on landfill?$t$,$b$A new plant could solve recurring rubbish collection problems and generate electricity. But residents near the chosen site worry about traffic and emissions, and the project would cost many millions of euros.$b$),
 (122,'south-africa',$t$Should Cape Town require all new homes to include rainwater harvesting tanks?$t$,$b$Tanks would ease pressure on dams during droughts and help households keep gardens and toilets going. They would, however, add several thousand rand to the price of new homes, including more modest ones.$b$),
 (123,'south-korea',$t$Should private cram schools nationwide be required to close by 10 p.m. for secondary pupils?$t$,$b$Late-night hagwon classes leave many teenagers short of sleep. A national 10 p.m. closing time would protect rest and health, but hagwon owners would lose income and some families feel it limits their children's exam preparation.$b$),
 (124,'spain',$t$Should Spain cut the standard working week to 37.5 hours with no reduction in pay?$t$,$b$A shorter week could improve work-life balance and health for millions of employees. The cost falls mostly on small businesses in hospitality and retail, which would have to hire more staff or absorb higher labour costs.$b$),
 (125,'colombia',$t$Should Colombia ban new cattle ranching on recently cleared Amazon forest land?$t$,$b$Pasture expansion is a major driver of deforestation in the Amazon regions of Caquetá and Guaviare. A ban would protect forest, but some rural families who rely on cattle would lose their main source of income.$b$),
 (126,'china',$t$Should Inner Mongolia stop approving new coal-fired power plants and shift investment to wind and solar?$t$,$b$The region has strong wind and sun and could cut emissions and air pollution. The cost falls on coal-mining towns, where jobs and local tax revenue depend on coal and retraining workers will take years.$b$),
 (127,'india',$t$Should Punjab meter electricity for farm tubewells and charge farmers for power above a free basic allowance?$t$,$b$Free, unmetered power encourages over-pumping and has drained groundwater across Punjab. Metering would conserve water and cut the state's subsidy bill, but it raises costs for farmers already under financial pressure.$b$),
 (128,'united-states',$t$Should Florida require all new homes to meet stricter hurricane-resistant roof and window standards?$t$,$b$Stronger construction reduces storm damage and could help stabilise home insurance costs. But it raises the price of new homes by thousands of dollars at a time when housing is already expensive for many Floridians.$b$),
 (129,'indonesia',$t$Should Komodo National Park charge foreign visitors a much higher entry fee to fund conservation?$t$,$b$Higher fees could limit crowds, protect Komodo dragons and pay for rangers. Local tour operators, boat owners and guesthouses in Labuan Bajo could lose business if fewer tourists visit.$b$),
 (130,'brazil',$t$Should Brazil raise taxes on sugary drinks and use the money for diabetes prevention in the SUS?$t$,$b$Diet-related illness puts growing pressure on the public health system. A higher tax would likely cut consumption and fund prevention, but it raises prices for consumers, often hitting poorer households most, and affects drink makers.$b$),
 (131,'russia',$t$Should Moscow charge private cars a daily fee to enter the city centre on weekdays?$t$,$b$A charge would ease congestion and air pollution in central Moscow and could fund public transport. But it adds a daily cost for drivers, including tradespeople and those without good metro links.$b$),
 (132,'pakistan',$t$Should Pakistan cut household gas subsidies and use the savings for targeted cash support to poorer families?$t$,$b$Blanket subsidies mostly benefit larger consumers and add to energy sector debt. Targeted support would be fairer and cheaper, but many middle-income families would see gas bills rise noticeably in winter.$b$),
 (133,'mexico',$t$Should Mexico raise its tax on sugary drinks to roughly two pesos per litre?$t$,$b$A higher tax could reduce diabetes and obesity and raise revenue for health. The cost falls hardest on lower-income households who buy these drinks, and on small corner shops whose sales depend on them.$b$),
 (134,'japan',$t$Should Japan allow private-car ride-hailing drivers in all cities, not only where taxis are short?$t$,$b$Wider ride-hailing would ease shortages at night and in tourist areas. The cost falls on licensed taxi drivers, whose incomes may drop, and raises questions about driver vetting and insurance for passengers.$b$),
 (135,'nigeria',$t$Should Nigeria require shops and markets to charge 50 naira for every plastic bag?$t$,$b$Discarded bags clog drains in cities and worsen urban flooding. A fee would cut use and could fund clean-ups, but it adds a small daily cost for low-income shoppers and is hard to enforce in open markets.$b$),
 (136,'philippines',$t$Should Boracay and El Nido set strict daily caps on tourist arrivals?$t$,$b$Caps would protect beaches, reefs and water supply from overcrowding. The cost is lost income for local resorts, boatmen and vendors, and disappointment for travellers who cannot get a slot.$b$),
 (137,'egypt',$t$Should Egypt gradually replace subsidised bread with equivalent cash transfers to families?$t$,$b$Cash transfers could cut waste and let families choose what to buy. The cost is risk: if prices rise faster than payments, poorer families lose the security of cheap daily bread they rely on.$b$),
 (138,'vietnam',$t$Should Hà Nội move Old Quarter street vendors from sidewalks into designated market zones?$t$,$b$Clearing sidewalks would make walking safer and easier for residents and visitors. But many vendors depend on passing foot traffic, and moving them could cut their daily income and change the street life people value.$b$),
 (139,'germany',$t$Should German states allow shops in city centres to open every Sunday?$t$,$b$Sunday opening could help city-centre retailers compete with online shopping and attract visitors. But retail workers would lose a protected day off, and small shops may struggle to staff the extra hours.$b$),
 (140,'bangladesh',$t$Should Bangladesh shut down brick kilns that still use old fixed-chimney technology?$t$,$b$Older kilns around Dhaka are a major source of winter smog. Closing them would improve air quality, but kiln owners and seasonal workers would lose income, and brick prices for construction could rise.$b$),
 (141,'turkey',$t$Should Türkiye review the minimum wage in lira twice a year instead of once?$t$,$b$More frequent reviews would help low-paid workers keep up with rising prices. But small businesses would face less predictable labour costs, and some may cut hours or hire fewer people as a result.$b$),
 (142,'iran',$t$Should Tehran start government office hours earlier in summer to cut peak electricity demand?$t$,$b$Opening earlier and closing before the hottest afternoon hours could ease strain on the power grid. But it disrupts commuting and childcare, and people who depend on those offices would have less time to reach them.$b$),
 (143,'united-kingdom',$t$Should local councils in the UK be allowed to add a small overnight levy on hotel and holiday stays?$t$,$b$Popular places such as the Lake District or Cornwall could use the money for toilets, bins and footpaths that visitors rely on. Hotels and B&Bs warn it raises prices and may push some visitors elsewhere.$b$),
 (144,'thailand',$t$Should Thailand charge foreign visitors an entry fee of a few hundred baht to fund national parks?$t$,$b$The money could pay for rangers, trail repairs and waste collection at busy parks and islands. Critics worry it adds cost and paperwork for travellers and could discourage some tourism in a sector many jobs depend on.$b$),
 (145,'france',$t$Should Paris cap short-term holiday rentals of main homes at 60 nights a year?$t$,$b$A lower cap could return more flats to long-term tenants in a tight rental market. But residents who rent out their home while travelling would lose income, and visitors would face fewer, pricier options.$b$),
 (146,'italy',$t$Should Italy reserve more of its coastline as free public beach instead of paid beach clubs?$t$,$b$Many beaches are leased to private stabilimenti with sunbeds and fees. More free beach would widen public access, but some beach businesses would lose their concessions and seasonal jobs could be lost.$b$),
 (147,'south-africa',$t$Should South Africa block new coal mines on high-value farmland in Mpumalanga?$t$,$b$Protecting the best soils and water sources would safeguard future food production. But mining provides many local jobs and tax revenue, and blocking new mines could mean fewer opportunities in the region.$b$),
 (148,'south-korea',$t$Should South Korea add a 300-won refundable deposit to every disposable takeaway coffee cup?$t$,$b$A deposit returned when the cup is brought back would cut litter and boost recycling. The cost falls on cafés, which must handle returns and storage, and on customers who pay more when they do not return cups.$b$),
 (149,'spain',$t$Should Spain tightly cap farm irrigation water around the Doñana wetlands?$t$,$b$Doñana's lagoons and aquifer have been drying out, threatening one of Europe's key bird habitats. Stricter limits would help it recover, but berry farmers and farm workers in Huelva would face lower harvests and lost jobs.$b$),
 (150,'colombia',$t$Should Bogotá extend its pico y placa driving restrictions to Saturdays?$t$,$b$Weekend traffic in Bogotá has grown, and extending number-plate restrictions could cut jams and pollution. The cost falls on families who use their only car for weekend errands and small businesses that rely on Saturday trade.$b$),
 (151,'china',$t$Should Chinese high schools extend compulsory evening study sessions until 10 p.m. to raise exam scores?$t$,$b$Longer supervised study hours might look like a way to lift gaokao results. But students already face long days, and less sleep and exercise tend to harm health and learning, so the extra hours may do more damage than good.$b$),
 (152,'india',$t$Should Mumbai ban all street food vendors from main roads to ease pedestrian and vehicle traffic?$t$,$b$Clearer pavements would help walkers and traffic flow. But lakhs of vendors depend on these spots for their livelihood, and many office workers and students rely on cheap street food, so a blanket ban could destroy incomes rather than organise them.$b$),
 (153,'united-states',$t$Should US elementary schools eliminate recess to add more instruction time in math and reading?$t$,$b$More classroom minutes sound like a direct route to higher test scores. But young children need breaks to focus, move and socialise, and removing recess tends to worsen attention, behaviour and physical health.$b$),
 (154,'indonesia',$t$Should motorcycles be allowed on Indonesia's intercity toll roads to ease congestion on ordinary roads?$t$,$b$It would give millions of riders faster routes, such as along the Trans-Java toll road. But mixing motorbikes with fast trucks and cars at highway speeds would greatly raise the risk of serious and fatal crashes.$b$),
 (155,'brazil',$t$Should Brazil freeze bus fares in all state capitals for five years to protect commuters?$t$,$b$A fare freeze would give riders certainty. But fuel and wage costs keep rising, so operators would either need large public subsidies or cut routes, frequency and maintenance, leaving commuters with worse service.$b$),
 (156,'russia',$t$Should Russian cities stop clearing snow from minor residential streets to save money?$t$,$b$Snow clearing is a large item in municipal budgets, so cutting it looks like an easy saving. But uncleared side streets would trap residents, block ambulances and fire engines, and cause more falls and injuries.$b$),
 (157,'pakistan',$t$Should Lahore ban motorcycles from its main arterial roads to improve traffic safety?$t$,$b$Motorcycle crashes are common, so a ban might seem like a safety fix. But motorbikes are the main affordable transport for millions of workers and students, and a ban would cut them off from jobs and classes.$b$),
 (158,'mexico',$t$Should Mexico use subsidies to guarantee that petrol never costs more than 20 pesos a litre?$t$,$b$A fixed pump price would shield drivers from global oil swings. But it could cost the treasury enormous sums in bad years, mostly benefit households that own cars, and weaken any incentive to use fuel more efficiently.$b$),
 (159,'japan',$t$Should Japan raise its sea walls along the entire Pacific coast to twice their current height?$t$,$b$Taller walls sound like strong tsunami protection. But the cost would be vast, the walls would cut fishing towns off from the sea, harm beaches and tourism, and could give residents false confidence to delay evacuating.$b$),
 (160,'nigeria',$t$Should Nigeria cap rents in its big cities at a fixed amount per room set by the state?$t$,$b$A cap sounds like quick relief for tenants in Lagos, Abuja and Port Harcourt. But fixed low rents tend to discourage new building and upkeep, so landlords may take units off the market or demand informal side payments.$b$),
 (161,'philippines',$t$Should the Philippines reclaim large areas of Manila Bay to build new housing quickly?$t$,$b$Reclaimed land could offer space for homes near the capital. But filling the bay can worsen flooding in coastal cities, destroy fishing grounds and mangroves, and new land is vulnerable to storm surge.$b$),
 (162,'egypt',$t$Should Egypt expand rice farming into desert land to become fully self-sufficient in rice?$t$,$b$Growing all its own rice sounds like food security. But rice is very water-hungry, and Egypt's Nile water is already stretched; diverting more to desert paddies would leave less for cities and other crops.$b$),
 (163,'vietnam',$t$Should Hà Nội ban motorbikes from all inner-city districts by 2028?$t$,$b$A ban promises cleaner air and quieter streets. But millions of people rely on motorbikes to get to work and school, and buses and metro lines are unlikely to be able to carry them all within a few years.$b$),
 (164,'germany',$t$Should Germany pay drivers a bonus to scrap working cars and buy new ones?$t$,$b$A scrappage bonus sounds like a boost to the car industry. But it destroys vehicles that still run, costs taxpayers billions of euros, and much of the money goes to households that would have bought a new car anyway.$b$),
 (165,'bangladesh',$t$Should Dhaka fill in its remaining canals and wetlands to build more roads?$t$,$b$New roads on filled land look like a quick fix for traffic. But canals and wetlands drain monsoon rainwater, and removing them would likely make flooding in the city far worse and harm fish and wildlife.$b$),
 (166,'turkey',$t$Should Türkiye allow extra floors on older apartment blocks in return for owner-funded renovation?$t$,$b$It sounds like a free way to renew old housing. But adding storeys can overload weak structures in an earthquake-prone country and crowds neighbourhoods whose roads, schools and water pipes were not built for more people.$b$),
 (167,'iran',$t$Should Iran let farmers drill deeper wells to pump more groundwater during droughts?$t$,$b$Deeper wells sound like a quick way to save harvests. But over-pumping drains aquifers that take decades to refill, causes land to sink under towns and farms, and leaves less water for everyone later.$b$),
 (168,'united-kingdom',$t$Should the UK relax rules to allow new housing estates on functional floodplains to speed up building?$t$,$b$Floodplain land is often flat, cheap and close to towns, so building there looks like a quick way to add homes. But these areas are meant to store floodwater, so new homes would face repeated flooding and push risk onto neighbours.$b$),
 (169,'thailand',$t$Should Bangkok remove all street food vendors from its main roads to widen pavements?$t$,$b$Clearer pavements would help pedestrians and wheelchair users. But street food feeds many workers cheaply and supports the incomes of tens of thousands of vendors, many of whom would lose their main source of living.$b$),
 (170,'france',$t$Should France build new low-altitude ski resorts in the Pyrenees to boost winter tourism?$t$,$b$New resorts promise jobs in quiet mountain valleys. But lower slopes are getting less reliable snow as winters warm, so resorts may depend on costly artificial snow and water use, and could close within years.$b$),
 (171,'italy',$t$Should Italian cities reopen historic-centre limited traffic zones to all private cars to help shops?$t$,$b$Letting cars back in sounds like a boost for local trade. But more traffic would bring noise, pollution and congestion to narrow medieval streets, and may damage monuments and make centres less pleasant to visit.$b$),
 (172,'south-africa',$t$Should South Africa's national parks allow self-drive visitors on the roads after dark?$t$,$b$Night driving could let more visitors see nocturnal animals and bring in extra income for parks. But it would raise the risk of collisions with wildlife, disturb animals, and make poaching harder to detect.$b$),
 (173,'south-korea',$t$Should South Korea reclaim more west-coast tidal flats to build new industrial parks?$t$,$b$Filling in mudflats would create flat land for factories and jobs near ports. But these getbol wetlands feed migratory birds and coastal fisheries, protect against storms, and once filled cannot be restored.$b$),
 (174,'spain',$t$Should Spain allow new homes to be built right up to the shoreline to ease the housing shortage?$t$,$b$Relaxing coastal building limits would open valuable land quickly. But beachfront construction worsens erosion, puts homes at risk from storms and rising seas, and would block public access to beaches that belong to everyone.$b$),
 (175,'colombia',$t$Should Colombia convert parts of the páramo highlands near Bogotá into new farmland?$t$,$b$Opening these high moorlands to farming could raise food output close to the capital. But páramos act like sponges that supply much of the drinking water for Bogotá and other cities, and damage to them is very slow to reverse.$b$),
 (176,'china',$t$Should Chengdu convert bicycle lanes on main roads into extra car lanes to reduce traffic jams?$t$,$b$More car lanes sound like a quick fix for congestion. But they tend to attract more driving, push cyclists and e-bike riders into dangerous mixed traffic, and undo years of investment in cleaner transport.$b$),
 (177,'india',$t$Should India permanently scrap tolls on all national highways to lower the cost of road travel?$t$,$b$Drivers and truckers would save money on every trip. But tolls fund construction and maintenance of highways, so removing them would leave a large funding gap that falls on general taxpayers or leads to worse roads.$b$),
 (178,'united-states',$t$Should farmers be allowed to pump unlimited water from the Ogallala Aquifer without permits or metering?$t$,$b$Removing limits would help Great Plains farmers grow more crops in the short term. But the aquifer refills very slowly, and unchecked pumping would drain it faster, leaving future farms and towns without water.$b$),
 (179,'indonesia',$t$Should coastal mangrove forests in Java be cleared for new shrimp farms to boost seafood exports?$t$,$b$Shrimp farming brings jobs and export income. But mangroves protect coastlines from erosion and storm surges and nurture fish stocks, and once cleared they take decades to recover, leaving villages more exposed.$b$),
 (180,'brazil',$t$Should Brazil let families build on hillsides without permits to speed up new housing?$t$,$b$Removing permits would let more homes go up quickly in cities short of housing. But unchecked building on steep slopes raises the risk of deadly landslides during heavy rains, as well as unsafe drainage and wiring.$b$),
 (181,'russia',$t$Should Russia put a high tax on imported fruit to encourage more home-grown produce?$t$,$b$The aim is to support domestic farmers. But much fruit cannot be grown in Russia's climate, especially in winter, so the main effect would be higher prices and less fresh fruit in household diets.$b$),
 (182,'pakistan',$t$Should Islamabad allow large housing projects in the Margalla Hills foothills to ease the housing shortage?$t$,$b$New housing near the capital could lower rents and create construction jobs. But the hills are a protected green area that shields the city's water supply and wildlife, and building there would cause lasting damage.$b$),
 (183,'mexico',$t$Should Mexico City pump more water from its aquifer to end neighbourhood water rationing quickly?$t$,$b$Extra wells could restore taps in rationed areas within months. But the aquifer is already over-used, and more pumping speeds up ground subsidence that cracks buildings, pipes and Metro lines across the city.$b$),
 (184,'japan',$t$Should Japan pay farmers to convert rice paddies into solar farms nationwide?$t$,$b$Solar on farmland could quickly add clean power and farmer income. But paddies also grow staple food, store rainwater that reduces flooding, and shape rural landscapes; large-scale conversion would weaken food security.$b$),
 (185,'nigeria',$t$Should Nigeria ban exports of raw cashew nuts to force all processing to happen locally?$t$,$b$The aim is to keep more value and jobs in Nigeria. But local processing capacity is limited, so a sudden ban could leave farmers with nuts they cannot sell, pushing prices down and encouraging smuggling across borders.$b$),
 (186,'philippines',$t$Should the Philippines set a low legal maximum price for rice in every market?$t$,$b$A price ceiling promises cheap rice for families. But if the cap is below cost, farmers and traders sell less, shortages and black markets can follow, and rice farmers' incomes fall.$b$),
 (187,'egypt',$t$Should Egypt allow new beach resorts to be built directly on Red Sea coral reef flats?$t$,$b$Building right at the water could add hotel rooms and jobs near Hurghada and Marsa Alam. But construction on reef flats kills coral, and the reefs are the main reason divers and snorkellers visit the coast.$b$),
 (188,'vietnam',$t$Should Hà Nội fill in more of its small lakes and ponds to create land for new housing?$t$,$b$New land could add homes in a crowded city. But these lakes and ponds hold rainwater during heavy storms, so filling them tends to make street flooding worse and removes cool, green public space.$b$),
 (189,'germany',$t$Should Germany require one parking space for every new apartment built in its cities?$t$,$b$Guaranteed parking sounds convenient for residents. But building garages adds a lot to construction costs, which pushes up rents and prices and uses land that could hold more homes near transit.$b$),
 (190,'bangladesh',$t$Should Bangladesh fix the retail price of rice at 40 taka per kilogram across the country?$t$,$b$A fixed low price sounds like help for struggling households. But if costs rise, sellers may hold back stock or sell on black markets, and farmers could earn too little to keep planting, leading to shortages.$b$),
 (191,'turkey',$t$Should Türkiye freeze all residential rents at current lira levels for five years?$t$,$b$A freeze would bring immediate relief to tenants. But landlords may stop maintaining homes, sell up or leave flats empty, and fewer new rentals would be built, making it harder to find a home over time.$b$),
 (192,'iran',$t$Should Iran build new dams on every seasonal river to store winter rainfall?$t$,$b$Storing more water looks like an answer to drought. But reservoirs in hot regions lose a lot to evaporation, and damming every river can dry out downstream wetlands, lakes and farms that depend on the flow.$b$),
 (193,'united-kingdom',$t$Should schools in the UK sell their playing fields to raise money for building repairs?$t$,$b$Selling land can raise large one-off sums for crumbling classrooms. But once playing fields are gone they are rarely replaced, leaving children with less space for sport and outdoor play for generations to come.$b$),
 (194,'thailand',$t$Should Bangkok fill in its remaining canals, or khlong, to create extra road lanes?$t$,$b$More road space sounds like a fix for traffic jams. But the khlong carry rainwater away during the monsoon, so filling them in would likely worsen flooding, and new lanes tend to fill up with more cars over time.$b$),
 (195,'france',$t$Should France close small rural post offices and move all their services online to save money?$t$,$b$Online services are cheaper to run than branch counters. But many rural residents, especially older people, rely on the local post office for parcels, cash and help with forms, and would be left with no nearby option.$b$),
 (196,'italy',$t$Should Liguria allow new housing on dry riverbeds to ease the shortage of flat building land?$t$,$b$Coastal Liguria has little flat land, so dry riverbeds look like easy sites. But these channels can fill quickly during heavy autumn rain, and building on them would put residents at serious risk of flooding.$b$),
 (197,'south-africa',$t$Should South Africa cut back school meal programmes to pay for more classroom tablets?$t$,$b$Tablets could help learners gain digital skills. But for many children the school meal is a key source of daily nutrition, and hungry learners struggle to concentrate, attend and learn, whatever the equipment.$b$),
 (198,'south-korea',$t$Should expressway speed cameras be switched off during Chuseok and Seollal to ease holiday traffic?$t$,$b$Turning cameras off during the big holiday journeys might feel like it lets traffic move faster. In practice it would encourage speeding on the busiest, most crowded days of the year, raising crash risk while barely shortening jams.$b$),
 (199,'spain',$t$Should Spain close its least-used regional train lines and spend the savings on more AVE routes?$t$,$b$Quiet rural lines cost money per passenger, while high-speed lines are popular. But closing them would cut off villages in already depopulated areas, forcing older residents without cars to lose access to towns and hospitals.$b$),
 (200,'colombia',$t$Should Bogotá end the Sunday Ciclovía and reopen those roads to cars all day?$t$,$b$Reopening the roads could ease some Sunday traffic for drivers. But it would take away free, safe space where huge numbers of residents walk, cycle and exercise each week, one of the city's most valued public spaces.$b$),
 (201,'china',$t$Should China formally name the peony as its national flower?$t$,$b$China has no officially designated national flower; the peony and the plum blossom have both been proposed over the years. The choice would appear on ceremonial material and souvenirs and change little else.$b$),
 (202,'india',$t$Should India Post issue a commemorative stamp series featuring the country's historic railway stations?$t$,$b$A stamp series could celebrate stations such as Chhatrapati Shivaji Maharaj Terminus and Howrah. It would please collectors at a very small printing cost, but would change little for most people either way.$b$),
 (203,'united-states',$t$Should the National Park Service adopt an official theme song for its park rangers?$t$,$b$A song could be played at visitor centers and ranger talks from Yellowstone to the Everglades. It would be a pleasant symbolic touch with negligible cost that changes nothing about how parks are run or protected.$b$),
 (204,'indonesia',$t$Should Indonesia adopt one official national kite design for international kite festivals?$t$,$b$Kite-flying is popular from Bali to Java, and each region has its own traditional shapes. An official design would appear on festival banners abroad, while local kite makers carried on exactly as before.$b$),
 (205,'brazil',$t$Should Brazil name brigadeiro its official national dessert for state banquets?$t$,$b$The chocolate sweet is served at countless birthday parties across the country. Making it the official dessert at state events would be a fun cultural nod, costing almost nothing and changing little in practice.$b$),
 (206,'russia',$t$Should Russia name the matryoshka doll an official symbol of national craftsmanship?$t$,$b$Nesting dolls are already a well-known folk craft and popular souvenir. An official title might add a little pride and tourist appeal, but it would not change how crafts are made, sold or supported.$b$),
 (207,'pakistan',$t$Should Pakistan designate an official national mango variety for government gift boxes?$t$,$b$Pakistan grows many celebrated varieties such as Chaunsa, Sindhri and Anwar Ratol. Choosing one for official gifts would be a pleasant symbolic choice with little practical effect on farmers or exports.$b$),
 (208,'mexico',$t$Should Mexico name the axolotl the official mascot of the national postal service?$t$,$b$The axolotl, native to Xochimilco's canals, is already a popular national symbol. Making it the postal service's mascot would appear on stamps and posters, but it would not change delivery times, prices or service.$b$),
 (209,'japan',$t$Should Japan choose an official national cloud shape for weather forecast graphics?$t$,$b$Forecast maps use many slightly different cloud icons across broadcasters. A single official shape would look tidy, but it would not make forecasts any more accurate or change how people prepare for weather.$b$),
 (210,'nigeria',$t$Should Nigeria officially declare jollof rice its national dish at state banquets?$t$,$b$Jollof rice is already widely loved and served at celebrations. Making it the official banquet dish would be a symbolic gesture for cultural pride and tourism, with little cost and little practical change for anyone.$b$),
 (211,'philippines',$t$Should the Philippines declare an official national sunset-viewing day each year?$t$,$b$Sunsets over Manila Bay and many coasts are well loved. A named day would appear on calendars but would not be a holiday, and it would change nothing about work, schools or services.$b$),
 (212,'egypt',$t$Should Egypt adopt an official national colour for the sails of Nile feluccas?$t$,$b$Felucca sails in Aswan and Cairo are mostly white or cream. An official colour might look distinctive in photos, but owners could ignore it and it would change nothing about river transport or tourism.$b$),
 (213,'vietnam',$t$Should Hội An use the phrase “Lantern Evenings” on official signs for its full-moon nights?$t$,$b$Hội An already holds lantern-lit evenings on full-moon nights. This would only standardise the wording on a few tourist signs; nothing about the event itself, its timing or its cost would change.$b$),
 (214,'germany',$t$Should Germany name an official “Bread of the Year” on the federal calendar?$t$,$b$The country’s bread culture is already widely celebrated. Choosing one loaf each year for an official mention would be a small cultural gesture that affects no budgets, laws or bakeries’ trade.$b$),
 (215,'bangladesh',$t$Should Bangladesh hold an annual national day to celebrate the hilsa fish?$t$,$b$Hilsa is a much-loved part of Bangladeshi cooking. A yearly celebration day with food fairs would be a cheerful cultural event, but it would not change fishing rules, prices or anything else of substance.$b$),
 (216,'turkey',$t$Should Türkiye mark an official National Simit Day on the calendar?$t$,$b$A named day would celebrate the popular sesame bread ring with no holiday or public spending attached. Bakeries might run a promotion, but it would change nothing of substance for anyone.$b$),
 (217,'iran',$t$Should Isfahan decorate its new manhole covers with traditional tile patterns?$t$,$b$New covers would carry a simple pattern inspired by the city’s historic tilework, at almost the same cost as plain ones. It would be a small visual touch with no real effect on services or budgets.$b$),
 (218,'united-kingdom',$t$Should the UK formally adopt the robin as its official national bird?$t$,$b$The robin is already a familiar garden visitor and a common sight on Christmas cards. Giving it official status would be a gentle, symbolic gesture with no practical effect on wildlife protection or people's lives.$b$),
 (219,'thailand',$t$Should Thailand choose an official cartoon mascot for its Songkran water festival?$t$,$b$A friendly mascot could appear on posters and souvenirs during the April new year celebrations. It would cost little and change nothing about how the festival works; people would celebrate in the same way either way.$b$),
 (220,'france',$t$Should the Paris Métro give each of its lines a name in addition to its number?$t$,$b$Lines are currently known by numbers and colours. Adding names, perhaps after rivers or writers, would be a charming touch, but travellers would still find their way in exactly the same manner as before.$b$),
 (221,'italy',$t$Should each Italian region choose an official pasta shape for its tourism brochures?$t$,$b$Liguria might pick trofie and Puglia orecchiette, printed on posters and regional websites. It is branding only: menus, farming and the pasta trade would be unaffected.$b$),
 (222,'south-africa',$t$Should South Africa declare malva pudding its official national dessert?$t$,$b$Malva pudding is a well-loved dessert served at family meals and restaurants. Making it official would be a fun symbolic gesture, but it would not change what anyone cooks, eats or pays for.$b$),
 (223,'south-korea',$t$Should South Korea name an official national snack for the summer monsoon season?$t$,$b$Many people enjoy pancakes like pajeon on rainy jangma days. Naming an official monsoon snack would be a light cultural gesture with no cost to anyone, and would not change what people actually eat.$b$),
 (224,'spain',$t$Should Spain hold a yearly national vote to choose an official tapa of the year?$t$,$b$Each spring the public would pick one tapa to celebrate, from patatas bravas to pimientos de Padrón. It would be a friendly bit of food culture with negligible cost and no real effect on what bars serve.$b$),
 (225,'colombia',$t$Should Colombia declare an official national fruit from its many tropical varieties?$t$,$b$Colombia grows a wide range of fruits, from lulo and guanábana to maracuyá. Choosing one as an official national fruit would be a pleasant symbolic gesture with no real cost and no change to farming or trade.$b$),
 (226,'china',$t$Should China's high-speed trains name their dining cars after regional teas?$t$,$b$Dining cars could carry names such as Longjing, Pu'er or Tieguanyin on their signs and menus. It is decoration only: the food, fares and timetables would stay exactly the same.$b$),
 (227,'india',$t$Should India choose an official cartoon mascot to announce the arrival of the monsoon each year?$t$,$b$A friendly mascot could appear on weather bulletins and school posters when the India Meteorological Department declares the monsoon onset. It is a light-hearted symbolic idea with negligible cost or practical effect.$b$),
 (228,'united-states',$t$Should official US government documents call daylight saving time 'summer time' instead?$t$,$b$The change would only affect wording on federal websites and forms, not when the clocks change. It would cost little and make no practical difference to schedules, energy use or daily life.$b$),
 (229,'indonesia',$t$Should Indonesia create an official cartoon mascot for batik appreciation day each October?$t$,$b$A mascot could appear on school posters and social media to celebrate batik heritage. It is a light symbolic idea with negligible cost that would do little to change how batik is made, sold or worn.$b$),
 (230,'brazil',$t$Should Brasília give its residential superblocks poetic names alongside their number codes?$t$,$b$The capital's superquadras are known by codes such as SQS 308. Adding names inspired by Cerrado plants would be a small cultural touch, while the existing addresses and postal codes would stay exactly the same.$b$),
 (231,'russia',$t$Should Trans-Siberian trains play a short melody when they cross from Europe into Asia?$t$,$b$A tune at the Urals crossing would be a small memorable moment for passengers on the long journey. It would cost little and change nothing about ticket prices, travel times or service.$b$),
 (232,'pakistan',$t$Should Islamabad paint all benches in its public parks one standard colour?$t$,$b$A single colour could give parks such as Fatima Jinnah Park a uniform look. Repainting would happen during routine maintenance at minimal cost and would make no real difference to how people use the parks.$b$),
 (233,'mexico',$t$Should the Mexico City Metro give each of its line colours an official poetic name?$t$,$b$Lines are known by number and colour. Poetic names such as 'jacaranda' for pink might charm riders, but they would add no trains, shorten no waits, and would cost little beyond updated signs.$b$),
 (234,'japan',$t$Should Shinkansen trains play a different gentle chime as they enter each prefecture?$t$,$b$A short regional melody at each prefecture border could delight passengers. It would cost little to program, but it would not affect speed, safety, fares or anything else about the journey.$b$),
 (235,'nigeria',$t$Should Abuja give its major roundabouts names taken from Nigerian rivers?$t$,$b$Naming roundabouts after rivers such as the Niger, Benue and Kaduna could make directions a little more memorable for visitors. It would require new signs but would not change traffic, services or daily life in any real way.$b$),
 (236,'philippines',$t$Should every Philippine province adopt an official provincial seashell?$t$,$b$Many provinces already have official flowers or festivals. A provincial seashell could be featured on tourism leaflets, but it would not protect reefs or beaches and would have little practical effect.$b$),
 (237,'egypt',$t$Should Egypt adopt jasmine as its official national scent for state occasions?$t$,$b$Jasmine has long been grown in the Nile Delta for the perfume trade. An official scent would be used at receptions and on ceremonial gifts, and would make no practical difference to anyone's daily life.$b$),
 (238,'vietnam',$t$Should Đà Lạt paint its public park benches in the colours of local hydrangeas?$t$,$b$Benches would be repainted in soft blues and pinks when they are next due for maintenance anyway. It is a small cosmetic choice with no real effect on budgets, tourism numbers or daily life.$b$),
 (239,'germany',$t$Should Berlin give each of its U-Bahn lines an official nickname alongside its number?$t$,$b$Lines would keep their numbers and colours but gain a friendly name on maps. It would change nothing about service, fares or trains and cost little beyond updating signs when they are next replaced.$b$),
 (240,'bangladesh',$t$Should Bangladesh print a water lily on the cover of every government school exercise book?$t$,$b$The water lily is a well-known national symbol. Printing it on school notebooks would be a small decorative touch that changes neither the cost of books nor what or how pupils learn.$b$),
 (241,'turkey',$t$Should İstanbul ferries play a short, gentle chime before each departure?$t$,$b$Passengers would hear a brief melody in addition to the existing horn and announcements. It costs very little and is purely atmospheric; timetables, fares and safety would not change.$b$),
 (242,'iran',$t$Should Iran’s postal service issue a stamp series featuring Persian cats?$t$,$b$A themed stamp set would celebrate a well-known breed and might please collectors. Stamps are already printed each year, so this changes only the design, with no real effect on postal services or costs.$b$),
 (243,'united-kingdom',$t$Should the Met Office give official names to major heatwaves, as it already does for storms?$t$,$b$Named heatwaves might be easier to talk about in the news. The practical warnings, advice and forecasts would stay exactly the same, so the change would mostly affect headlines rather than what people actually do.$b$),
 (244,'thailand',$t$Should each Chao Phraya Express Boat pier get a small painted emblem next to its number?$t$,$b$Piers along the river are known by name and number. A painted emblem such as a lotus or a heron would decorate the signs and maps; the boats, routes and fares would run exactly as before.$b$),
 (245,'france',$t$Should French motorway rest areas display a short poem by a French author at each stop?$t$,$b$A poem on a panel could give drivers something pleasant to read while they stretch their legs. It would cost little and have no real effect on road safety, traffic or the journey itself.$b$),
 (246,'italy',$t$Should Italy give each of its coastal lighthouses an official poetic nickname?$t$,$b$Lighthouses along the coast from Sicilia to Liguria could each receive a nickname for maps and tourist leaflets. It would cost little and have no effect on navigation, safety or anyone's daily life.$b$),
 (247,'south-africa',$t$Should SANParks design a special typeface for all signs in South Africa's national parks?$t$,$b$A custom font could give park signs a distinctive, unified look. Visitors would still read directions and rules the same way, and the change would make little practical difference to conservation or visits.$b$),
 (248,'south-korea',$t$Should South Korean public libraries stamp returned books with a small seasonal illustration?$t$,$b$A returned book might get a stamped cherry blossom in April or a persimmon in autumn on its date slip. It would cost next to nothing, please some readers, and change nothing about how libraries work.$b$),
 (249,'spain',$t$Should Spain adopt an official national lullaby for new-parent welcome packs?$t$,$b$Regional nanas and lullabies vary widely across Spain. One would be printed, with its score, in the packs some health services give new parents; families would sing whatever they already sing.$b$),
 (250,'colombia',$t$Should Medellín give each Metrocable cabin its own name taken from a local flower?$t$,$b$Every cable car cabin would carry a small plaque with the name of a flower, nodding to the city's flower festival. It would cost very little and would make no difference to how the cable car lines operate.$b$)
  ) AS t(ord, forum, title, body)
  JOIN forums f ON f.slug = t.forum;

COMMIT;

-- What you should see: 250 questions, 25 forums with 10 each, 0 ballots,
-- 5 test agents, and 0 titles that are not questions.
SELECT (SELECT count(*) FROM issues) AS questions,
       (SELECT count(DISTINCT forum_id) FROM issues) AS forums_used,
       (SELECT count(*) FROM issues WHERE forum_id IS NULL) AS without_forum,
       (SELECT count(*) FROM votes)  AS ballots,
       (SELECT count(*) FROM agents a JOIN users u ON u.id = a.user_id
         WHERE u.email LIKE '%@dd.test') AS test_agents,
       (SELECT count(*) FROM issues WHERE title NOT LIKE '%?') AS titles_not_questions;
