-- 100 sample questions, for seeing what the site looks like with something in
-- it. Deliberately mixed: some plainly worth doing, some plainly not, and a
-- good number that should land in the contested quadrant if the agents are
-- reading properly. If everything comes back "supported", the prompt is being
-- too agreeable and that is worth knowing early.
--
--   docker compose exec -T postgres psql -U vote -d vote -f - < sample_issues.sql
--
-- Authored by the lowest-numbered account. Safe to run twice: it skips titles
-- that already exist.

INSERT INTO issues (author_id, title, body, closes_at, created_at)
SELECT (SELECT id FROM users ORDER BY id LIMIT 1),
       t.title, t.body,
       now() + ((((t.ord * 5) % 20) + 2) * interval '1 day'),
       now() - (t.ord * interval '70 minutes')
  FROM (VALUES
 (1,$t$Should all buses be free at weekends?$t$,$b$Saturday and Sunday travel at no charge across the municipal network. Roughly 8% of fare revenue, against a reduction in weekend car journeys.$b$),
 (2,$t$Should private cars be banned from the old town between 07:00 and 19:00?$t$,$b$Pedestrians, cyclists, deliveries and transit buses only. Residents keep permits for their own street. Fourteen shops on Storgatan rely on customers parking outside.$b$),
 (3,$t$Should one parking space per street become a bike rack?$t$,$b$One space in ten becomes covered cycle parking. Costs about 40 000 kr per street and removes roughly 300 car spaces citywide.$b$),
 (4,$t$Should delivery vans be charged by weight for old-town access?$t$,$b$A sliding fee by vehicle weight during the day. Aimed at consolidating deliveries rather than banning them.$b$),
 (5,$t$Should night trains be subsidised to replace domestic flights under 600 km?$t$,$b$Municipal co-funding for sleeper services, conditional on the operator matching it. The airport loses two daily routes.$b$),
 (6,$t$Should rental e-scooters be banned entirely?$t$,$b$Remove all shared scooters from public space. Ends pavement clutter and a steady stream of A&E visits; also removes a genuinely used way to get home at night.$b$),
 (7,$t$Should the urban speed limit be lowered to 30 km/h everywhere?$t$,$b$A blanket 30 limit inside the ring road. Journey times rise by two to four minutes; collisions at 30 are survivable in a way they are not at 50.$b$),
 (8,$t$Should parking be free for everyone over 70?$t$,$b$Free municipal parking on production of ID. Costs about 3 million kr a year and mostly benefits those who already drive.$b$),
 (9,$t$Should there be a rush-hour congestion charge with revenue ring-fenced for cycling?$t$,$b$30 kr to enter the centre 07:00-09:00 and 16:00-18:00. Every krona goes to protected bike lanes. Falls hardest on shift workers without transit options.$b$),
 (10,$t$Should bicycle helmets be mandatory for adults?$t$,$b$Fines for riding without one. Reduces head injuries per cyclist; the evidence elsewhere is that it also reduces the number of cyclists.$b$),
 (11,$t$Should short-term holiday lets be capped at 60 nights a year?$t$,$b$Above 60 nights a property needs a commercial licence. Returns flats to the long-term market; cuts income for people letting a spare room.$b$),
 (12,$t$Should buildings up to six storeys be allowed without a planning hearing?$t$,$b$By-right construction up to six storeys on any plot already zoned residential. Faster housing, less say for neighbours.$b$),
 (13,$t$Should every new large building provide a publicly accessible toilet?$t$,$b$Any new building over 2000 square metres must provide a toilet open to the street during business hours.$b$),
 (14,$t$Should petrol leaf blowers be banned within the city?$t$,$b$Electric blowers and rakes remain legal. One petrol blower emits more hydrocarbons in an hour than a car driven to Stockholm.$b$),
 (15,$t$Should a tree be planted for every child born in the municipality?$t$,$b$About 900 trees a year, sited in the new district. Families are invited to the planting.$b$),
 (16,$t$Should all municipal roofs be painted white?$t$,$b$Reflective coatings on schools, offices and the depot. Cuts summer cooling cost; marginally raises winter heating.$b$),
 (17,$t$Should one lane of the main street become a linear park?$t$,$b$Four lanes become three, with the fourth given to trees, seating and a cycle track.$b$),
 (18,$t$Should chickens be allowed in residential gardens?$t$,$b$Up to six hens, no roosters, minimum distance from the boundary. Eggs, compost and noise complaints.$b$),
 (19,$t$Should planning permission be refused for new drive-through restaurants?$t$,$b$Existing ones continue. Applies only to new applications inside the ring road.$b$),
 (20,$t$Should every new flat be required to have a balcony or shared terrace?$t$,$b$Adds roughly 4% to construction cost per unit and rules out some of the cheapest designs.$b$),
 (21,$t$Should there be a deposit scheme for takeaway coffee cups?$t$,$b$10 kr deposit, refunded at any participating cafe. Cafes handle the washing; the municipality funds the racks.$b$),
 (22,$t$Should municipal buildings stop selling bottled water?$t$,$b$Fountains and refill points instead. Saves about 180 000 bottles a year.$b$),
 (23,$t$Should every household get municipal food waste collection?$t$,$b$Separate brown bin, fortnightly. Requires eleven new vehicles and produces biogas for the bus fleet.$b$),
 (24,$t$Should the beavers be allowed to re-flood the eastern wetland?$t$,$b$Stop removing the dams. Restores 40 hectares of wetland and floods a footpath and two hectares of grazing land.$b$),
 (25,$t$Should street lighting be dimmed to 30% after 01:00?$t$,$b$Excludes main roads and the station approach. Saves energy and returns a visible night sky; some residents will feel less safe.$b$),
 (26,$t$Should household waste be charged by weight?$t$,$b$A per-kilo rate replacing the flat fee. Rewards reducing waste; falls hardest on large households and on nappies.$b$),
 (27,$t$Should private fireworks be banned in favour of two municipal displays?$t$,$b$Ends the fortnight of bangs around New Year. Dogs, veterans and night workers benefit; a tradition ends.$b$),
 (28,$t$Should solar panels be required on all new roofs?$t$,$b$Any new building over 100 square metres. Adds cost up front, pays back in roughly nine years at current prices.$b$),
 (29,$t$Should the municipal golf course be rewilded?$t$,$b$Convert 60 hectares to meadow and woodland with public paths. The club has 400 members and a lease until 2031.$b$),
 (30,$t$Should single-use disposable barbecues be banned?$t$,$b$Following two grass fires last summer. Permanent grills to be installed in the three main parks.$b$),
 (31,$t$Should every algorithm used in benefits decisions be listed in a public register?$t$,$b$Not the source code: a plain-language entry saying what each system does, what data it uses, and who is accountable for it.$b$),
 (32,$t$Should all council meeting minutes be published within 48 hours?$t$,$b$Currently they appear within three weeks, often after the decision has taken effect.$b$),
 (33,$t$Should municipal broadband be run as a utility?$t$,$b$Fibre to every address at cost, wholesale access for any retail provider. Capital cost around 400 million kr.$b$),
 (34,$t$Should facial recognition be banned in publicly accessible spaces?$t$,$b$Applies to the municipality and to private operators of spaces the public can enter. Exemption only for a court order.$b$),
 (35,$t$Should new municipal systems be required to use open-source software?$t$,$b$Where a viable option exists. Reduces lock-in; narrows the supplier field and may cost more up front.$b$),
 (36,$t$Should every resident get a secure digital mailbox for official post?$t$,$b$Opt-out rather than opt-in. Saves postage; excludes people who do not use computers unless paper is maintained in parallel.$b$),
 (37,$t$Should the salary of every public official above a threshold be published?$t$,$b$All municipal posts paid above 700 000 kr a year, published annually by role and name.$b$),
 (38,$t$Should part of the budget be decided by a citizens' assembly chosen by lottery?$t$,$b$Fifty residents drawn at random, paid for their time, deciding 2% of the capital budget.$b$),
 (39,$t$Should political advertising be banned on municipal property?$t$,$b$No party posters on bus shelters, bins or hoardings the municipality owns, in any season.$b$),
 (40,$t$Should every council committee be livestreamed?$t$,$b$Including the planning committee, with archives kept for five years.$b$),
 (41,$t$Should municipal staff trial a four-day week at full pay?$t$,$b$Twelve-month trial in two departments, with published results. Requires roughly 15% more staff in front-line roles.$b$),
 (42,$t$Should school meals be free for every pupil regardless of income?$t$,$b$Removes the means test and the stigma with it. Costs about 24 million kr a year, some of it subsidising families who could pay.$b$),
 (43,$t$Should dental care be free up to the age of 25?$t$,$b$Extends the current limit of 23. Dental problems compound; early treatment is cheaper than late.$b$),
 (44,$t$Should every 16-year-old be guaranteed a paid summer job?$t$,$b$Three weeks at the minimum youth rate, in parks, care homes and libraries.$b$),
 (45,$t$Should municipal carers be paid on the nurses' scale?$t$,$b$Raises about 900 salaries. The work is comparable; the budget line is not.$b$),
 (46,$t$Should the municipality refuse to advertise unpaid internships?$t$,$b$The municipality neither offers nor hosts unpaid placements, and will not list them on its job board.$b$),
 (47,$t$Should there be a right to disconnect outside working hours?$t$,$b$No expectation of answering work messages between 18:00 and 07:00, written into municipal contracts.$b$),
 (48,$t$Should municipal employees get one paid day a year for volunteering?$t$,$b$Municipal employees may take a working day for registered voluntary work.$b$),
 (49,$t$Should universal basic services be piloted in one district?$t$,$b$Free transport, water and broadband for every household in a single district for two years, with a proper evaluation.$b$),
 (50,$t$Should language classes be free for anyone who wants them?$t$,$b$Open to all residents, evenings and weekends, no eligibility test at the door.$b$),
 (51,$t$Should municipal offices have a mandatory quiet hour from 13:00 to 14:00?$t$,$b$No meetings, no calls. Proposed by the occupational health team after a survey on interruptions.$b$),
 (52,$t$Should every street in the new district be named after a local tree?$t$,$b$Alm, Ask, Bok, Ek, Lind. Cheaper than commemorating people and nobody later objects to the tree.$b$),
 (53,$t$Should a public swimming pool be built in the harbour?$t$,$b$A floating pool with filtered sea water, open June to September. Capital cost about 18 million kr.$b$),
 (54,$t$Should the municipality appoint an official cat?$t$,$b$Resident at the library, on the payroll at one tin a day, with a page on the website.$b$),
 (55,$t$Should the dress code for council meetings be abolished?$t$,$b$No requirement for a tie or jacket. Proposed on the grounds that it deters younger candidates.$b$),
 (56,$t$Should a slide be installed beside the station stairs?$t$,$b$A stainless steel slide next to the main staircase, as in Utrecht. Cost about 300 000 kr.$b$),
 (57,$t$Should there be a town-wide silent hour on Sunday mornings?$t$,$b$No mowing, no drilling, no blowers before 10:00 on Sundays. Enforced by complaint, not patrol.$b$),
 (58,$t$Should residents name the new bridge by public vote?$t$,$b$Nominations open for a month, a shortlist of five, then a binding vote. The obvious risk is well documented.$b$),
 (59,$t$Should a bandstand be built with a free concert every Sunday?$t$,$b$Summer season, local musicians paid the union rate. Roughly 600 000 kr a year including the fee budget.$b$),
 (60,$t$Should ice cream be free on the hottest day of the year?$t$,$b$Declared by the municipality when the forecast passes 30 degrees. About 120 000 kr, and it would be remembered for years.$b$),
 (61,$t$Should feeding pigeons carry a 2 000 kr fine?$t$,$b$Enforced by wardens in the square. Aimed at reducing the flock; would in practice be issued mostly to pensioners.$b$),
 (62,$t$Should library cards carry an annual charge?$t$,$b$200 kr a year, free for under-18s. Raises about 1.4 million kr against a library budget of 60 million.$b$),
 (63,$t$Should the central park be sold to close the budget gap?$t$,$b$Development land worth roughly 180 million kr, enough to cover two years of deficit. The park is 90 years old.$b$),
 (64,$t$Should librarians be replaced with self-service kiosks?$t$,$b$Retain two staff per branch for maintenance. Saves 11 million kr a year and removes the person who helps people apply for things.$b$),
 (65,$t$Should public benches be removed from the station area?$t$,$b$Proposed to discourage people sleeping and drinking there. The benches are also used by everyone waiting for a bus.$b$),
 (66,$t$Should admission be charged for the municipal beach?$t$,$b$50 kr a day in July and August, residents free on production of ID.$b$),
 (67,$t$Should every bus have audio-recording CCTV?$t$,$b$Continuous recording of conversations as well as images, retained for 30 days.$b$),
 (68,$t$Should the names of everyone with unpaid parking fines be published?$t$,$b$A monthly list on the municipal website until the fine is paid.$b$),
 (69,$t$Should busking be banned in the town centre?$t$,$b$Following eleven complaints last year about amplified performance on the pedestrian street.$b$),
 (70,$t$Should the swimming pool close from November to March?$t$,$b$Saves 4 million kr in heating. The pool is where the schools teach swimming.$b$),
 (71,$t$Should a permit be required for any gathering of more than three people in a park?$t$,$b$Applications 14 days in advance, 400 kr fee. Intended to manage large events.$b$),
 (72,$t$Should the night bus be cut entirely?$t$,$b$Services after 00:30 carry an average of nine passengers. They are the way home for care and hospitality staff.$b$),
 (73,$t$Should domestic rainwater collection be taxed?$t$,$b$A charge on private water butts, on the argument that collected rainwater bypasses the drainage levy.$b$),
 (74,$t$Should public drinking fountains be removed to save maintenance?$t$,$b$Eleven fountains, about 200 000 kr a year in servicing and winterisation.$b$),
 (75,$t$Should schools be charged for their waste collection?$t$,$b$Moves the cost from the waste budget to the education budget, changing nothing about the waste.$b$),
 (76,$t$Should a small modular reactor be built on the coast?$t$,$b$300 MW, twelve-year horizon. Firm low-carbon power, a waste question nobody has finished answering, and a site the fishing fleet uses.$b$),
 (77,$t$Should the entire bus fleet be replaced with electric at twice the cost?$t$,$b$Eleven years earlier than the replacement schedule requires. Cleaner air now, at 340 million kr brought forward.$b$),
 (78,$t$Should streets outside every school close at drop-off and pick-up?$t$,$b$No through traffic 08:00-09:00 and 14:00-15:30. Safer approaches; displaced parking onto surrounding streets.$b$),
 (79,$t$Should 16-year-olds be allowed to vote in municipal elections?$t$,$b$For local elections only. They are affected by school and transport decisions and cannot currently vote on them.$b$),
 (80,$t$Should rent increases be capped at inflation for five years?$t$,$b$Applies to all tenancies in the municipality. Protects existing tenants; the effect on new construction is the argument.$b$),
 (81,$t$Should 2 000 flats be built on the green belt?$t$,$b$On 30 hectares of protected land at the northern edge. The housing queue is currently nine years.$b$),
 (82,$t$Should supermarkets be allowed to open 24 hours?$t$,$b$Removes the current closing requirement. Convenience for shift workers; night work for staff who did not choose it.$b$),
 (83,$t$Should a tourist tax of 30 kr per night be introduced?$t$,$b$Collected by hotels, spent on the things tourists use. Roughly 22 million kr a year.$b$),
 (84,$t$Should residents have a veto over any building above four storeys?$t$,$b$Any adjoining resident may block a taller proposal. Local control over the skyline; a further obstacle to housing.$b$),
 (85,$t$Should the two smallest village schools be merged?$t$,$b$Saves 6 million kr a year. The journey for the younger children becomes 25 minutes each way.$b$),
 (86,$t$Should naming rights to the arena be sold?$t$,$b$A ten-year sponsorship worth about 4 million kr a year. The arena is named after the town.$b$),
 (87,$t$Should advertising aimed at children be banned in public space?$t$,$b$No advertising directed at under-12s on municipal property, including bus shelters near schools.$b$),
 (88,$t$Should the Christmas lights budget be spent on a heated day room instead?$t$,$b$2.1 million kr moved from decorations to a warm space open through the winter.$b$),
 (89,$t$Should the town centre become a low-emission zone?$t$,$b$Older diesel vehicles excluded from 2028. Cleaner air; a real cost to tradespeople with older vans.$b$),
 (90,$t$Should every municipal contract over 10 million kr be published in full?$t$,$b$Including prices. Bidders say it will raise their prices; residents cannot currently see what was agreed.$b$),
 (91,$t$Should the municipality fund a repair cafe with paid staff?$t$,$b$A workshop with tools and two part-time technicians. Fixes about 40 items a week and trains people to do it themselves.$b$),
 (92,$t$Should bus travel be free for anyone registered as unemployed?$t$,$b$Interviews, appointments and the rest. Costs about 5 million kr a year.$b$),
 (93,$t$Should there be a drinking fountain every 400 metres in the centre?$t$,$b$Twenty-two new fountains, winterised. Capital 3 million kr, maintenance 400 000 a year.$b$),
 (94,$t$Should the public library start a seed library?$t$,$b$Borrow seeds in spring, return seeds in autumn. Almost free, and it builds a local variety over time.$b$),
 (95,$t$Should beehives be put on every school roof?$t$,$b$With a beekeeper on contract and the honey sold at the school fair. One allergy question per school to resolve first.$b$),
 (96,$t$Should school playgrounds be open at weekends?$t$,$b$Unlocked Saturday and Sunday, 09:00-19:00. Requires a caretaker rota and accepting some vandalism.$b$),
 (97,$t$Should there be a tool library alongside the book library?$t$,$b$Borrow a drill instead of buying one. Start-up 700 000 kr, then staffing within the existing rota.$b$),
 (98,$t$Should swimming lessons be free for every eight-year-old?$t$,$b$Ten lessons during school hours. Drowning is a leading cause of death for children in this country.$b$),
 (99,$t$Should the old water tower become a public viewpoint?$t$,$b$A lift, a platform and a small cafe. About 30 million kr for a building currently costing money to keep standing.$b$),
 (100,$t$Should there be a weekly producers' market on the main square?$t$,$b$Saturdays, stalls let at cost to growers within 80 km. Displaces 40 parking spaces for the day.$b$)
  ) AS t(ord, title, body)
 WHERE EXISTS (SELECT 1 FROM users)
   AND NOT EXISTS (SELECT 1 FROM issues i WHERE i.title = t.title);
